ARG MONGOOSE_VERSION

FROM emcmongoose/mongoose-storage-driver-service-base:${MONGOOSE_VERSION}

ADD ["./build/libs/mongoose-storage-driver-swift.jar", "/opt/mongoose/ext/mongoose-storage-driver-swift.jar"]
